//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int buttonBack = 2131034112;
			
			// aapt resource value: 0x7f05001e
			public const int myButton = 2131034142;
			
			// aapt resource value: 0x7f050001
			public const int tv001 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int tv002 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int tv003 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int tv004 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int tv005 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int tv006 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int tv007 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int tv008 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int tv009 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int tv010 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int tv011 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int tv012 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int tv013 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int tv014 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int tv015 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int tv016 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int tv017 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int tv018 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int tv019 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int tv020 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int tv021 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int tv022 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int tv023 = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int tv024 = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int tv025 = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int tv026 = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int tv027 = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int tv028 = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int tv029 = 2131034141;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Act2 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
